version: "3"
services:
  node:
    image: "node:15.8-buster"
    volumes:
      - ".:/opt/nextjs-blog"
    tty: true
    command: ["bash", "-c", "cd /opt/nextjs-blog && npm run dev"]
    ports:
      - "3000:3000"
